name: metrics
on:
  schedule:
    - cron: "0 0 * * *"   # once a day
  workflow_dispatch:      # lets you trigger it manually from the Actions tab

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_achievements: yes
          config_timezone: Africa/Cairo
